apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-port
  - port: 9121
    targetPort: 9121
    name: redis-exporter-port
    nodePort: 30002